name: Performance Tests ⚡

on: push

jobs:
    k6-load-test:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout código do repositório
              uses: actions/checkout@v4

            - name: Instalar o k6
              run: |
                  sudo apt update
                  sudo snap install k6

            - name: Rodar Teste de Performance e gerar JSON
              run: npm run test

            - name: Salvar Relatório de Performance
              uses: actions/upload-artifact@v4
              with:
                  name: k6-performance-report
                  path: results/results.json
